[window]
opacity = 0.8

dimensions = { columns = 275, lines = 300 }

position = { x = 1500, y = 0 }

padding = { x = 8, y = 8 }

[font]
size = 13

[shell]
program = "/usr/local/bin/fish"
args = ["-l", "-c", "tmux a -t 0 || tmux"]
